version: '3'

services:
  ldap:
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    volumes:
      - ldap_var:/var/lib/ldap
      - ldap_etc:/etc/ldap/slapd.d

  ldap-admin:
    image: osixia/phpldapadmin
    links:
      - ldap
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
volumes:
  ldap_var:
  ldap_etc:
