#!/bin/sh
#
#  This role installs docker upon the new guest system.
#
#

prefix=$1

#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi



#
# Log our start
#
logMessage Script $0 starting


#
#  Install docker
#
chroot ${prefix} docker swarm init
installDebianPackage ${prefix} docker network create --driver overlay --attachable portainer_agent_network
installDebianPackage ${prefix} docker service create \
    --name portainer_agent \
    --network portainer_agent_network \
    --publish mode=host,target=9001,published=9001 \
    -e AGENT_CLUSTER_ADDR=tasks.portainer_agent \
    --mode global \
    --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
    --mount type=bind,src=//var/lib/docker/volumes,dst=/var/lib/docker/volumes \
    portainer/agent

    
#
#  Log our finish
#
logMessage Script $0 finished
