version: '3'

services:
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql
    ports:
      - "5151:80"
    links:
      - mysql-server
    depends_on:
      - mysql-server
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Europe/Paris
      - ZBX_SERVER_NAME=Zabbix
      - DB_SERVER_HOST=mysql-server
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=secret
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    ports:
      - "10051:10051"
    links:
      - mysql-server
    depends_on:
      - mysql-server
    environment:
      - PHP_TZ=Europe/Paris
      - DB_SERVER_HOST=mysql-server
      - DB_SERVER_PORT=3306
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=secret
  zabbix-agent:
    image: zabbix/zabbix-agent
    links:
      - zabbix-server
    environment:
      - ZBX_SERVER_HOST=zabbix-server
  mysql-server:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql_zabbix:/var/lib/mysql
volumes:
  mysql_zabbix:
